apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-api-deployment
  labels:
    app: banking-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-api
  template:
    metadata:
      labels:
        app: banking-api
    spec:
      containers:
      - name: banking-api
        image: 379128660891.dkr.ecr.ap-southeast-1.amazonaws.com/banking:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080